---
name: Neovim
on:
  pull_request: ~
  push:
    paths-ignore:
      - "*.md"
    branches:
      - main

jobs:
  ubuntu:
    name: Ubuntu
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Install Neovim
        uses: MunifTanjim/setup-neovim-action@v1
        with:
          tag: nightly
      - name: Run neovim
        run: |
          nvim --version
          nvim --headless -u test/init.lua +q
  windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Neovim
        run: |
          C:\msys64\usr\bin\wget.exe -q https://github.com/neovim/neovim/releases/download/nightly/nvim-win64.zip
          7z x nvim-win64.zip
          Add-Content $env:GITHUB_PATH ".\nvim-win64\bin\"
      - name: Run neovim
        run: |
          nvim --version
          nvim --headless -u test/init.lua +q
